###afficher repo
GET http://localhost:3000/api/repos

### create repo
POST  http://localhost:3000/api/repos
Content-Type: application/json

{
    "id": "bobobobo",
    "name": "lebeausite",
    "url": "http://lebeausite.com",
    "status": 1
  }


### afficher language

GET http://localhost:3000/api/langue

### Afficher status

GET http://localhost:3000/api/status

### create status
POST http://localhost:3000/api/status
Content-Type: application/json

{
    
    "label": "privé"
  }